version: "3.1"

services:
  web:
    container_name: docker-web
    image: nginx:1.17
    networks:
      - default
    ports:
      - "8080:80"
    volumes:
      - ./settings/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html

  php-fpm:
    container_name: docker-php-fpm
    build: ./settings/php-fpm
    networks:
      - default
    volumes:
      - ./html:/var/www/html

  db:
    container_name: docker-db
    image: mariadb:10.4
    networks:
      - default
    volumes:
      - ./db-datas:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop

  phpmyadmin:
    container_name: docker-phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0
    networks:
      - default
    ports:
      - "8090:80"
    volumes:
      - /sessions
    environment:
      PMA_HOST: db

networks:
  default:
