version: "3.0"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
  php-fpm:
    image: php:7.4-fpm
    volumes:
      - ./html:/usr/share/nginx/html
